apiVersion: apps/v1
kind: Deployment
metadata:
  name: Database-deployment
  labels:
    app: Database-MySQL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Database-MySQL
  template:
    metadata:
      labels:
        app: Database-MySQL
    spec:
      containers:
      - name: Database-MySQL
        image: yagofontoura222@database-mysql:1.0
        ports:
        - containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yagofontoura222@:1.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer